
import { WorkNode, NodeId } from '../canon/schema/ir';

/**
 * A logical step generated by the Planner.
 */
export interface Step {
    id: string;
    description: string;
    required_context_keys: string[]; // e.g. ["user_profile", "project_history"]
    complexity?: 'simple' | 'complex';
    substeps?: Step[]; // For recursive subdivision
}

/**
 * The output of the Planner.
 * Represents specific intents.
 */
export interface Plan {
    goal: string;
    steps: Step[];
}

/**
 * Defines what needs to be retrieved for a Plan.
 */
export interface RetrievalRequest {
    query: string;
    filters?: {
        types?: WorkNode['type'][];
        tags?: string[];
    };
}

/**
 * Context container for a compilation run.
 * This is what flows through the pipeline.
 */
export interface CompilerContext {
    jobId: string;
    goal: string;
    plan?: Plan;
    retrieved_nodes: WorkNode[];
    // Could track errors, artifacts, etc.
}
